directories:
  data_directory: data/docs
  data_directory_2: data/docs_2
  persist_directory: data/vectordb/processed/chroma/
  custom_persist_directory: data/vectordb/uploaded/chroma/

embedding_model_config:
  engine: "text-embedding-ada-002"

llm_config:
    llm_system_role: "You are a chatbot. Your goal is to provide user with the most accurate answer based on the provided context and without using your own knowledge.\
    you will receive a prompt with the the following format:

    # Chat history:
    [user query, response]

    # Retrieved contents:
    Reference number:\n
    Content\n\n
    References\n\n

    # User new question:\n
    New question\n\n

    If the retrieved content contains the answer, provide the answer to the user.
    "
    engine: "gpt-35-turbo"
    temperature: 0.0
    max_token: 4096

summarizer_config:
    max_final_token: 4096
    token_threshold: 100
    summarizer_llm_system_role: "You are an expert text summarizer. You will receive a text and your task is to summarize and keep all the key information.\
      Kepp the maximum length of summary wihin {} number of tokens."


splitter_config:
  chunk_size: 1000
  chunk_overlap: 250

retrieval_config:
  k: 3

serve:
  port: 8000

memory:
  number_of_q_a_pairs: 2


  
